import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {JSDOM} from 'jsdom';
import {indexedDB} from 'fake-indexeddb';
import {templatePoints,frameRecord,analyzeRom} from '../dist/analysis.mjs';

test('등록 → 최종 결과 → 상세 수정/취소/반영 → 저장 복원 (DOM 통합)',async()=>{
  const html=await readFile(new URL('../dist/index.html',import.meta.url),'utf8');
  const dom=new JSDOM(html,{url:'https://example.test',pretendToBeVisual:true});
  const w=dom.window;
  for(const key of ['window','document','localStorage','HTMLElement','Image','FileReader'])globalThis[key]=key==='window'?w:w[key];
  Object.defineProperty(globalThis,'navigator',{value:w.navigator,configurable:true});
  globalThis.indexedDB=indexedDB;globalThis.confirm=()=>true;globalThis.requestAnimationFrame=cb=>setTimeout(cb,0);
  w.scrollTo=()=>{};w.HTMLElement.prototype.scrollIntoView=()=>{};
  w.HTMLMediaElement.prototype.pause=()=>{};w.HTMLMediaElement.prototype.load=()=>{};
  const ctx=new Proxy({createLinearGradient:()=>({addColorStop(){}})},{get:(o,k)=>o[k]??(()=>{}),set:(o,k,v)=>(o[k]=v,true)});
  w.HTMLCanvasElement.prototype.getContext=()=>ctx;
  const app=await import('../dist/app.js');
  assert.equal(w.document.body.dataset.view,'capture');assert.equal(w.document.querySelector('#final-analysis').disabled,true);
  w.document.querySelector('#temporary-patient').click();
  for(const code of ['AB','FE2','FE','ER','BIR','IRER']) {
    const frames=Array.from({length:10},(_,index)=>{const points=templatePoints(index/9*Math.PI);for(const p of Object.values(points)){p.visibility=1;p.status='detected';p.aspectRatio=16/9;}return{...frameRecord({index,time:index/30,motion:code,points}),sourceFrame:index};});
    const rom=analyzeRom(frames,'right',code,{cirStartFrame:0,cirEndFrame:9});
    Object.assign(app.state.sessions[code],{frames,fileName:code+'.mp4',fileSize:100,sourceFile:new Blob(['test-video'],{type:'video/mp4'}),rom,autoRom:structuredClone(rom),analysisStatus:rom?.valid?'complete':'review',autoRepresentativeFrame:rom?.representativeFrameIndex,finalRepresentativeFrame:rom?.representativeFrameIndex,measuredArm:'right'});
  }
  app.setView('capture');assert.equal(w.document.querySelector('#final-analysis').disabled,false);
  w.document.querySelector('#final-analysis').click();assert.equal(w.document.body.dataset.view,'results');assert.equal(w.document.querySelectorAll('.final-motion').length,4);
  const original=structuredClone(app.state.sessions.FE);
  app.openDetail('FE');assert.equal(w.document.body.dataset.view,'detail');assert.notEqual(app.session(),app.state.sessions.FE);
  const landmarks=w.document.querySelector('#landmark-list').textContent;assert.match(landmarks,/왼쪽 골반/);assert.doesNotMatch(landmarks,/왼쪽 팔꿈치/);assert.match(landmarks,/오른쪽 팔꿈치/);
  app.session().frames[0].corrected.right_elbow.x=.12;
  assert.deepEqual(app.state.sessions.FE,original,'수정 중에는 최종값을 변경하지 않음');
  w.document.querySelector('#discard-detail').click();assert.equal(w.document.body.dataset.view,'results');assert.deepEqual(app.state.sessions.FE,original);
  app.openDetail('FE');app.session().frames[0].corrected.right_elbow.x=.12;app.session().frames[0].corrected.right_elbow.status='manual';
  await app.applyDetail();assert.equal(w.document.body.dataset.view,'results');assert.equal(app.state.sessions.FE.frames[0].corrected.right_elbow.x,.12);assert.deepEqual(app.state.sessions.FE.autoRom,original.autoRom);assert.deepEqual(app.state.sessions.FE.frames[0].raw,original.frames[0].raw);
  const payload=app.patientPayload();assert.doesNotThrow(()=>app.validateImport(payload));assert.equal(payload.measurements.FE.hideOppositeArm,true);assert.equal(payload.measurements.FE.displayTrunk,true);
  const unsavedExit=new w.Event('beforeunload',{cancelable:true});w.dispatchEvent(unsavedExit);assert.equal(unsavedExit.defaultPrevented,true);
  w.document.querySelector('#save-final').click();
  await new Promise(r=>setTimeout(r,40));
  assert.ok(w.document.querySelector('#saved-patients').options.length>1);
  assert.ok(w.document.querySelector('#toast').textContent.includes('저장'));
  const db=await new Promise((resolve,reject)=>{const request=indexedDB.open('shoulder-rom-lab',2);request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error);});
  const saved=await new Promise(resolve=>{const request=db.transaction('exams').objectStore('exams').get(payload.examId);request.onsuccess=()=>resolve(request.result);});
  assert.equal(saved.schemaVersion,'5.0');assert.equal(await saved.videos.FE.text(),'test-video');
  assert.equal(saved.criteria.label,'동작 의심도점수');db.close();
  const savedExit=new w.Event('beforeunload',{cancelable:true});w.dispatchEvent(savedExit);assert.equal(savedExit.defaultPrevented,false);
  w.document.querySelector('#load-patient').click();await new Promise(r=>setTimeout(r,80));
  assert.equal(await app.state.sessions.FE.sourceFile.text(),'test-video');
  assert.ok(app.state.sessions.FE.videoUrl.startsWith('blob:'));
  const beforeWeight=app.state.criteria.weights.AB;
  const input=w.document.querySelector('[data-code="AB"][data-field="weight"]');input.value='99';
  w.document.querySelector('#v5-settings-save').click();
  assert.equal(app.state.criteria.weights.AB,beforeWeight);
  assert.match(w.document.querySelector('#v5-settings-state').textContent,/100/);
  const $=s=>w.document.querySelector(s);
  $('#v5-settings-button').click();assert.equal(w.document.body.dataset.admin,'true');assert.equal($('#v5-settings').hidden,false);
  assert.equal($('#camera-device').closest('#v52-camera-defaults')!==null,true);
  $('#v52-start').value='3';$('#v52-return').value='2';$('#v52-boundary-0').value='25';$('#v52-boundary-1').value='60';$('#v52-save-settings').click();
  assert.deepEqual(app.state.criteria.stages.boundaries,[25,60]);assert.equal(JSON.parse(localStorage.getItem('shoulder:v52:capture')).startSeconds,3);
  assert.deepEqual(app.patientPayload().criteria.stages.boundaries,[25,60]);
  $('#v52-boundary-0').value='90';$('#v52-save-settings').click();assert.deepEqual(app.state.criteria.stages.boundaries,[25,60]);assert.match($('#v52-settings-status').textContent,/경계/);
  assert.equal($('#v52-video-input').accept,'video/*');assert.equal($('#bir-tracking').value,'wrist');
  assert.equal($('#v52-files').querySelectorAll('.v52-file').length,4);
  // Exercise the actual upload -> frozen still -> editable points -> versioned save UI.
  const neutralVideo=$('#v52-video');
  for(const [k,v]of Object.entries({videoWidth:640,videoHeight:360,readyState:2,duration:2}))Object.defineProperty(neutralVideo,k,{value:v,configurable:true});
  neutralVideo.load=()=>setTimeout(()=>neutralVideo.dispatchEvent(new w.Event('loadeddata')),0);
  w.HTMLCanvasElement.prototype.toDataURL=()=> 'data:image/jpeg;base64,AAAA';
  globalThis.createImageBitmap=async()=>({close(){}});
  globalThis.Worker=class{postMessage(data){const poses=Array.from({length:33},()=>({x:.5,y:.5,visibility:1}));poses[12]={x:.5,y:.2,visibility:1};poses[14]={x:.5,y:.4,visibility:1};poses[16]={x:.5,y:.6,visibility:1};poses[24]={x:.5,y:.7,visibility:1};setTimeout(()=>this.onmessage({data:{id:data.id,delegate:'CPU',poses:[poses]}}),0);}terminate(){}};
  const neutralFile=new File([new Uint8Array([0,0])],'neutral.webm',{type:'video/webm'});
  Object.defineProperty($('#v52-video-input'),'files',{value:[neutralFile],configurable:true});$('#v52-video-input').dispatchEvent(new w.Event('change'));
  await new Promise(r=>setTimeout(r,30));assert.match($('#v52-source').textContent,/neutral.webm/);
  $('#v52-capture').click();await new Promise(r=>setTimeout(r,30));assert.equal($('#v52-save-neutral').disabled,false);
  assert.equal($('#v52-points').querySelectorAll('input').length,8);
  const wrist=$('#v52-points input[aria-label="right_wrist x"]');wrist.value='.51';wrist.dispatchEvent(new w.Event('change'));
  $('#v52-save-neutral').click();await new Promise(r=>setTimeout(r,30));assert.match($('#v52-neutral-status').textContent,/새 기준 저장 완료/);
  $('#v52-use-neutral').click();assert.match($('#v52-neutral-status').textContent,/기준 선택 적용됨/);
  const {templateStore}=await import('../dist/neutral.mjs');const templates=await templateStore('list');assert.equal(templates.length,1);assert.equal(templates[0].source.kind,'upload');assert.equal(templates[0].corrected.right_wrist.x,.51);assert.equal(templates[0].raw.right_wrist.x,.5);
  $('#v52-admin-close').click();assert.equal(w.document.body.dataset.admin,'false');
  // PC defaults must not silently rewrite the active exam's measurement policy.
  const priorCriteria=structuredClone(app.state.criteria);
  $('#full-bir').value='20';$('#full-step').value='5';$('#full-arm').value='left';$('#full-save').click();
  assert.deepEqual(app.state.criteria,priorCriteria);
  assert.equal(JSON.parse(localStorage.getItem('shoulder:v5:criteria')).birDivisions,20);
  assert.equal(app.state.defaults.frameStep,5);
  assert.equal(app.patientPayload().criteria.birDivisions,10);
  $('#full-reapply').click();assert.equal(app.state.criteria.birDivisions,20);assert.equal(app.patientPayload().criteriaHistory.at(-1).criteria.birDivisions,10);assert.equal(app.state.sessions.BIR.measurementSettings.birDivisions,20);assert.equal(app.state.sessions.IRER.measurementConfirmed,false);
  const invalid=structuredClone(app.patientPayload());invalid.measurements.FE2.fe2ExtensionFrame=999;
  assert.throws(()=>app.validateImport(invalid),/극점/);
  invalid.measurements.FE2.fe2ExtensionFrame=null;invalid.measurements.IRER.irerCalibration={arm:'right',reference:'wrist',forearm:-1,oppositeUpper:.2};
  assert.throws(()=>app.validateImport(invalid),/보정/);
  assert.equal($('#v52-view').value,'정면');$('#v52-motion').value='FE2';$('#v52-motion').dispatchEvent(new w.Event('change'));assert.equal($('#v52-view').value,'측면');
  assert.deepEqual([...w.document.querySelectorAll('.motion-card')].filter(x=>!x.hidden).map(x=>x.dataset.motion),['AB','FE2','BIR','IRER']);
  app.state.sessions.FE.videoUrl='blob:keep-on-back';
  const hide=new w.Event('pagehide');Object.defineProperty(hide,'persisted',{value:true});w.dispatchEvent(hide);
  assert.equal(app.state.sessions.FE.videoUrl,'blob:keep-on-back','뒤로가기 캐시 복귀 시 영상 연결 유지');
  app.queue.cancelAll();dom.window.close();
});
